package de.industria;

import de.industria.blocks.BlockAdvancedMovingBlock;
import de.industria.blocks.BlockBase;
import de.industria.blocks.BlockBurnable;
import de.industria.blocks.BlockBurnedCable;
import de.industria.blocks.BlockConveyorBelt;
import de.industria.blocks.BlockConveyorSpliter;
import de.industria.blocks.BlockConveyorSwitch;
import de.industria.blocks.BlockCornerBlockBase;
import de.industria.blocks.BlockElektricWire;
import de.industria.blocks.BlockEnderCore;
import de.industria.blocks.BlockFallingDust;
import de.industria.blocks.BlockFluidPipe;
import de.industria.blocks.BlockFluidValve;
import de.industria.blocks.BlockHangingVine;
import de.industria.blocks.BlockInfinityPowerSource;
import de.industria.blocks.BlockIronRod;
import de.industria.blocks.BlockItemDistributor;
import de.industria.blocks.BlockJigsaw;
import de.industria.blocks.BlockLeavesBase;
import de.industria.blocks.BlockLimestoneSheet;
import de.industria.blocks.BlockLogBase;
import de.industria.blocks.BlockMAirCompressor;
import de.industria.blocks.BlockMAlloyFurnace;
import de.industria.blocks.BlockMBlastFurnace;
import de.industria.blocks.BlockMBlender;
import de.industria.blocks.BlockMChunkLoader;
import de.industria.blocks.BlockMCoalHeater;
import de.industria.blocks.BlockMElectricFurnace;
import de.industria.blocks.BlockMFluidBath;
import de.industria.blocks.BlockMFluidInput;
import de.industria.blocks.BlockMFluidOutput;
import de.industria.blocks.BlockMFuseBox;
import de.industria.blocks.BlockMGenerator;
import de.industria.blocks.BlockMMultimeter;
import de.industria.blocks.BlockMPanelLamp;
import de.industria.blocks.BlockMPowerSwitch;
import de.industria.blocks.BlockMRaffinery;
import de.industria.blocks.BlockMSchredder;
import de.industria.blocks.BlockMSteamGenerator;
import de.industria.blocks.BlockMStoringCraftingTable;
import de.industria.blocks.BlockMThermalZentrifuge;
import de.industria.blocks.BlockMTransformatorCoil;
import de.industria.blocks.BlockMTransformatorContact;
import de.industria.blocks.BlockMarpleLeaves;
import de.industria.blocks.BlockMotor;
import de.industria.blocks.BlockNComputer;
import de.industria.blocks.BlockNetworkCable;
import de.industria.blocks.BlockPipePreassurizer;
import de.industria.blocks.BlockPowerEmiting;
import de.industria.blocks.BlockPreassurePipe;
import de.industria.blocks.BlockPreassurePipeItemTerminal;
import de.industria.blocks.BlockRAdvancedPiston;
import de.industria.blocks.BlockRAdvancedPistonHead;
import de.industria.blocks.BlockRButtonBlock;
import de.industria.blocks.BlockRConectorBlock;
import de.industria.blocks.BlockRControllPanel;
import de.industria.blocks.BlockRDCapacitor;
import de.industria.blocks.BlockRDPulseCounter;
import de.industria.blocks.BlockRHarvester;
import de.industria.blocks.BlockRHoverControler;
import de.industria.blocks.BlockRHoverExtension;
import de.industria.blocks.BlockRItemDetector;
import de.industria.blocks.BlockRLinearConector;
import de.industria.blocks.BlockRRadialConector;
import de.industria.blocks.BlockRRailPiston;
import de.industria.blocks.BlockRRedstoneContact;
import de.industria.blocks.BlockRRedstoneReciver;
import de.industria.blocks.BlockRSignalProcessorContact;
import de.industria.blocks.BlockReinforcedCasing;
import de.industria.blocks.BlockRubberLog;
import de.industria.blocks.BlockSalsolaSeeds;
import de.industria.blocks.BlockSaplingBase;
import de.industria.blocks.BlockSignalAntennaConector;
import de.industria.blocks.BlockSignalWire;
import de.industria.blocks.BlockStackedRedstoneTorch;
import de.industria.blocks.BlockStackedRedstoneWire;
import de.industria.blocks.BlockStructureScaffold;
import de.industria.blocks.BlockSwampAlgae;
import de.industria.blocks.BlockTInductiveRail;
import de.industria.blocks.BlockTRailAdapter;
import de.industria.blocks.BlockTSteelRail;
import de.industria.blocks.BlockTileBlock;
import de.industria.blocks.BlockTreeTap;
import de.industria.blocks.BlockWeathering;
import de.industria.fluids.BlockChemicalWater;
import de.industria.fluids.BlockCompressedAir;
import de.industria.fluids.BlockDestilledWater;
import de.industria.fluids.BlockNatronLye;
import de.industria.fluids.BlockOreSolution;
import de.industria.fluids.BlockRawOil;
import de.industria.fluids.BlockSteam;
import de.industria.fluids.BlockSulfuricAcid;
import de.industria.fluids.util.ItemFluidBucket;
import de.industria.fluids.util.ItemGasBucket;
import de.industria.items.ItemBase;
import de.industria.items.ItemBlueprint;
import de.industria.items.ItemBurneable;
import de.industria.items.ItemCutter;
import de.industria.items.ItemEmptyBlueprint;
import de.industria.items.ItemEnergyMeter;
import de.industria.items.ItemFluidMeter;
import de.industria.items.ItemFuse;
import de.industria.items.ItemHammer;
import de.industria.items.ItemHardDrive;
import de.industria.items.ItemNetworkConfigurator;
import de.industria.items.ItemProcessor;
import de.industria.items.ItemRemoteControll;
import de.industria.items.ItemSalsola;
import de.industria.items.ItemSchredderToolCrusher;
import de.industria.items.ItemStructureCladdingPane;
import de.industria.items.panelitems.ItemButtonElement;
import de.industria.items.panelitems.ItemLampElement;
import de.industria.items.panelitems.ItemLeverElement;
import de.industria.typeregistys.ModFluids;
import de.industria.typeregistys.ModSoundEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.item.Rarity;
import net.minecraft.util.ResourceLocation;

public class ModItems {
	
	// Redstone
	public static final Block pulse_counter = new BlockRDPulseCounter();
	public static final Block capacitor = new BlockRDCapacitor();
	public static final Block stacked_redstone_torch = new BlockStackedRedstoneTorch();
	public static final Block stacked_redstone_wire = new BlockStackedRedstoneWire();
	public static final Block advanced_piston = new BlockRAdvancedPiston(false, "advanced_piston");
	public static final Block advanced_piston_head = new BlockRAdvancedPistonHead("advanced_piston_head");
	public static final Block advanced_sticky_piston = new BlockRAdvancedPiston(true, "advanced_sticky_piston");
	public static final Block advanced_moving_block = new BlockAdvancedMovingBlock("advanced_moving_block");
	public static final Block redstone_reciver = new BlockRRedstoneReciver();
	public static final Block signal_wire = new BlockSignalWire();
	public static final Block antenna_conector = new BlockSignalAntennaConector();
	public static final Block linear_conector = new BlockRLinearConector();
	public static final Block signal_processor_contact = new BlockRSignalProcessorContact();
	public static final Block rail_piston = new BlockRRailPiston();
	public static final Block conector_block = new BlockRConectorBlock();
	public static final Block redstone_contact = new BlockRRedstoneContact();
	public static final Block button_block = new BlockRButtonBlock();
	public static final Block iron_rod = new BlockIronRod();
	public static final Block radial_conector = new BlockRRadialConector();
	public static final Block hover_controler = new BlockRHoverControler();
	public static final Block hover_extension = new BlockRHoverExtension();
	public static final Block controll_panel = new BlockRControllPanel();
	public static final Block harvester = new BlockRHarvester();
	public static final Block jigsaw = new BlockJigsaw();
	public static final Block item_detector = new BlockRItemDetector();
	public static final Block structure_scaffold = new BlockStructureScaffold("structure_scaffold");
	
	// TODO
	public static final Block storing_crafting_table = new BlockMStoringCraftingTable();	
	// Mechanic
	public static final Block motor = new BlockMotor();
	// Items
	//public static final Item sulfur_dioxid = new ItemBase("sulfur_dioxid", Industria.MATERIALS);
	
	// Networks
	public static final Block computer = new BlockNComputer();
	
	// Rail
	public static final Block steel_rail = new BlockTSteelRail();
	public static final Block inductive_rail = new BlockTInductiveRail();
	public static final Block rail_adapter = new BlockTRailAdapter();
	
	// Machinery
	public static final Block conveyor_switch = new BlockConveyorSwitch();
	public static final Block conveyor_spliter = new BlockConveyorSpliter();
	public static final Block conveyor_belt = new BlockConveyorBelt();
	public static final Block generator = new BlockMGenerator();
	public static final Block infinity_power_source = new BlockInfinityPowerSource();
	public static final Block panel_lamp = new BlockMPanelLamp();
	public static final Block copper_cable = new BlockElektricWire("copper_cable", 16, 4);
	public static final Block electrolyt_copper_cable = new BlockElektricWire("electrolyt_copper_cable", 32, 4);
	public static final Block aluminium_cable = new BlockElektricWire("aluminium_cable", 64, 8);
	public static final Block burned_cable = new BlockBurnedCable();
	public static final Block network_cable = new BlockNetworkCable();
	public static final Block fluid_pipe = new BlockFluidPipe();
	public static final Block fluid_valve = new BlockFluidValve();
	public static final Block fluid_input = new BlockMFluidInput();
	public static final Block fluid_output = new BlockMFluidOutput();
	public static final Block steam_generator = new BlockMSteamGenerator();
	public static final Block coal_heater = new BlockMCoalHeater();
	public static final Block transformator_contact = new BlockMTransformatorContact();
	public static final Block transformator_coil = new BlockMTransformatorCoil();
	public static final Block fuse_box = new BlockMFuseBox();
	public static final Block multimeter = new BlockMMultimeter();
	public static final Block power_switch = new BlockMPowerSwitch();
	public static final Block electric_furnace = new BlockMElectricFurnace();
	public static final Block schredder = new BlockMSchredder();
	public static final Block blender = new BlockMBlender();
	public static final Block raffinery = new BlockMRaffinery();
	public static final Block alloy_furnace = new BlockMAlloyFurnace();
	public static final Block thermal_zentrifuge = new BlockMThermalZentrifuge();
	public static final Block fluid_bath = new BlockMFluidBath();
	public static final Block chunk_loader = new BlockMChunkLoader();
	public static final Block blast_furnace = new BlockMBlastFurnace();
	public static final Block preassure_pipe = new BlockPreassurePipe();
	public static final Block pipe_preassurizer = new BlockPipePreassurizer();
	public static final Block air_compressor = new BlockMAirCompressor();
	public static final Block item_distributor = new BlockItemDistributor();
	
	// Ore and Resource Blocks
	public static final Block bauxit = new BlockBase("bauxit", Material.ROCK, 1.5F, SoundType.STONE);
	public static final Block bauxit_ore = new BlockBase("bauxit_ore", Material.ROCK, 1.5F, SoundType.STONE);
	public static final Block wolframit = new BlockBase("wolframit", Material.ROCK, 1.5F, SoundType.STONE);
	public static final Block wolframit_ore = new BlockBase("wolframit_ore", Material.ROCK, 1.5F, SoundType.STONE);
	public static final Block copper_ore = new BlockBase("copper_ore", Material.ROCK, 3F, SoundType.STONE);
	public static final Block tin_ore = new BlockBase("tin_ore", Material.ROCK, 3F, SoundType.STONE);
	public static final Block silver_ore = new BlockBase("silver_ore", Material.ROCK, 3F, SoundType.STONE);
	public static final Block palladium_ore = new BlockBase("palladium_ore", Material.ROCK, 4F, 3F, SoundType.STONE);
	public static final Block nickel_ore = new BlockBase("nickel_ore", Material.ROCK, 3F, SoundType.STONE);
	public static final Block sulfur_ore = new BlockBase("sulfur_ore", Material.ROCK, 3F, SoundType.NETHER_ORE);
	public static final Block copper_block = new BlockBase("copper_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block redstone_alloy_block = new BlockPowerEmiting("redstone_alloy_block", Material.IRON, 5F, 6F, SoundType.METAL, 8);
	public static final Block aluminium_block = new BlockBase("aluminium_block", Material.IRON, 2F, 4F, SoundType.METAL);
	public static final Block electrolyt_copper_block = new BlockBase("electrolyt_copper_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block steel_block = new BlockBase("steel_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block monel_block = new BlockBase("monel_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block nickel_block = new BlockBase("nickel_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block wolfram_block = new BlockBase("wolfram_block", Material.IRON, 7F, 10F, SoundType.METAL);
	public static final Block silver_block = new BlockBase("silver_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block palladium_block = new BlockBase("palladium_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block tin_block = new BlockBase("tin_block", Material.IRON, 5F, 6F, SoundType.METAL);
	public static final Block cardboard_block = new BlockBurnable("cardboard_block", Material.WOOL, 0.2F, 2.5F, ModSoundEvents.CARDBOARD, 400, 30, 60, true);
	public static final Block preassure_pipe_item_terminal = new BlockPreassurePipeItemTerminal();
	
	// Deko Blocks
	public static final Block clean_cladding_white = new BlockTileBlock("clean_cladding_white");
	public static final Block clean_cladding_black = new BlockTileBlock("clean_cladding_black");
	public static final Block oxidized_copper_planks = new BlockBase("oxidized_copper_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block oxidized_tin_planks = new BlockBase("oxidized_tin_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block oxidized_iron_planks = new BlockBase("oxidized_iron_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block weathered_copper_planks = new BlockWeathering("weathered_copper_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_copper_planks);
	public static final Block weathered_tin_planks = new BlockWeathering("weathered_tin_planks", Material.IRON, 2.5F, 3F, SoundType.METAL,oxidized_tin_planks);
	public static final Block weathered_iron_planks = new BlockWeathering("weathered_iron_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_iron_planks);
	public static final Block exposed_copper_planks = new BlockWeathering("exposed_copper_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_copper_planks);
	public static final Block exposed_tin_planks = new BlockWeathering("exposed_tin_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_tin_planks);
	public static final Block exposed_iron_planks = new BlockWeathering("exposed_iron_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_iron_planks);
	public static final Block oxidized_copper_plates = new BlockBase("oxidized_copper_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block oxidized_tin_plates = new BlockBase("oxidized_tin_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block oxidized_iron_plates = new BlockBase("oxidized_iron_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block oxidized_steel_plates = new BlockBase("oxidized_steel_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block oxidized_steel_planks = new BlockBase("oxidized_steel_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block weathered_copper_plates = new BlockWeathering("weathered_copper_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_copper_plates);
	public static final Block weathered_tin_plates = new BlockWeathering("weathered_tin_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_tin_plates);
	public static final Block weathered_iron_plates = new BlockWeathering("weathered_iron_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_iron_plates);
	public static final Block weathered_steel_plates = new BlockWeathering("weathered_steel_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_steel_plates);
	public static final Block weathered_steel_planks = new BlockWeathering("weathered_steel_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, oxidized_steel_planks);
	public static final Block exposed_copper_plates = new BlockWeathering("exposed_copper_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_copper_plates);
	public static final Block exposed_tin_plates = new BlockWeathering("exposed_tin_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_tin_plates);
	public static final Block exposed_iron_plates = new BlockWeathering("exposed_iron_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_iron_plates);
	public static final Block exposed_steel_plates = new BlockWeathering("exposed_steel_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_steel_plates);
	public static final Block exposed_steel_planks = new BlockWeathering("exposed_steel_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, weathered_steel_planks);
	public static final Block gold_plates = new BlockBase("gold_plates", Material.IRON, 1.5F, 2.2F, SoundType.METAL);
	public static final Block iron_plates = new BlockWeathering("iron_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_iron_plates);
	public static final Block netherite_plates = new BlockBase("netherite_plates", Material.IRON, 25F, 600F, SoundType.NETHERITE);
	public static final Block copper_plates = new BlockWeathering("copper_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_copper_plates);
	public static final Block aluminium_plates = new BlockBase("aluminium_plates", Material.IRON, 1.5F, 2F, SoundType.METAL);
	public static final Block electrolyt_copper_plates = new BlockBase("electrolyt_copper_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block steel_plates = new BlockWeathering("steel_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_steel_plates);
	public static final Block redstone_alloy_plates = new BlockPowerEmiting("redstone_alloy_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, 4);
	public static final Block tin_plates = new BlockWeathering("tin_plates", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_tin_plates);
	public static final Block silver_plates = new BlockBase("silver_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block palladium_plates = new BlockBase("palladium_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block wolfram_plates = new BlockBase("wolfram_plates", Material.IRON, 3.5F, 3.7F, SoundType.METAL);
	public static final Block nickel_plates = new BlockBase("nickel_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block monel_plates = new BlockBase("monel_plates", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block gold_planks = new BlockBase("gold_planks", Material.IRON, 1.5F, 2F, SoundType.METAL);
	public static final Block iron_planks = new BlockWeathering("iron_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_iron_planks);
	public static final Block copper_planks = new BlockWeathering("copper_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_copper_planks);
	public static final Block aluminium_planks = new BlockBase("aluminium_planks", Material.IRON, 1.5F, 2F, SoundType.METAL);
	public static final Block electrolyt_copper_planks = new BlockBase("electrolyt_copper_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block steel_planks = new BlockWeathering("steel_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_steel_planks);
	public static final Block redstone_alloy_planks = new BlockPowerEmiting("redstone_alloy_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, 4);
	public static final Block tin_planks = new BlockWeathering("tin_planks", Material.IRON, 2.5F, 3F, SoundType.METAL, exposed_tin_planks);
	public static final Block silver_planks = new BlockBase("silver_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block palladium_planks = new BlockBase("palladium_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block wolfram_planks = new BlockBase("wolfram_planks", Material.IRON, 3.5F, 3.7F, SoundType.METAL);
	public static final Block nickel_planks = new BlockBase("nickel_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block monel_planks = new BlockBase("monel_planks", Material.IRON, 2.5F, 3F, SoundType.METAL);
	public static final Block netherite_planks = new BlockBase("netherite_planks", Material.IRON, 25F, 600F, SoundType.NETHERITE);
	public static final Block chiseled_smooth_stone = new BlockBase("chiseled_smooth_stone", Material.ROCK, 2F, 6F, SoundType.STONE);
	public static final Block smooth_cobblestone = new BlockBase("smooth_cobblestone", Material.ROCK, 2F, 6F, SoundType.STONE);
	public static final Block salt_block = new BlockBase("salt_block", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block salt_bricks = new BlockBase("salt_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block cracked_salt_bricks = new BlockBase("cracked_salt_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block polished_andesite_bricks = new BlockBase("polished_andesite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block polished_diorite_bricks = new BlockBase("polished_diorite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block polished_granite_bricks = new BlockBase("polished_granite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block polished_wolframite_bricks = new BlockBase("polished_wolframite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block polished_bauxite_bricks = new BlockBase("polished_bauxite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block cracked_polished_andesite_bricks = new BlockBase("cracked_polished_andesite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block cracked_polished_diorite_bricks = new BlockBase("cracked_polished_diorite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block cracked_polished_granite_bricks = new BlockBase("cracked_polished_granite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block cracked_polished_wolframite_bricks = new BlockBase("cracked_polished_wolframite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block cracked_polished_bauxite_bricks = new BlockBase("cracked_polished_bauxite_bricks", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block limestone = new BlockBase("limestone", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block limestone_sheet = new BlockLimestoneSheet();
	public static final Block polished_wolframite = new BlockBase("polished_wolframite", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block polished_bauxite = new BlockBase("polished_bauxite", Material.ROCK, 1.5F, 6F, SoundType.STONE);
	public static final Block white_painted_planks = new BlockBurnable("white_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block orange_painted_planks = new BlockBurnable("orange_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block magenta_painted_planks = new BlockBurnable("magenta_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block light_blue_painted_planks = new BlockBurnable("light_blue_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block yellow_painted_planks = new BlockBurnable("yellow_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block lime_painted_planks = new BlockBurnable("lime_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block pink_painted_planks = new BlockBurnable("pink_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block gray_painted_planks = new BlockBurnable("gray_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block light_gray_painted_planks = new BlockBurnable("light_gray_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block cyan_painted_planks = new BlockBurnable("cyan_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block purple_painted_planks = new BlockBurnable("purple_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block blue_painted_planks = new BlockBurnable("blue_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block brown_painted_planks = new BlockBurnable("brown_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block green_painted_planks = new BlockBurnable("green_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block red_painted_planks = new BlockBurnable("red_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	public static final Block black_painted_planks = new BlockBurnable("black_painted_planks", Material.WOOD, 2, 3, SoundType.WOOD, 5, 20, 300 , true);
	
	public static final Block stone_corner = new BlockCornerBlockBase("stone_corner", () -> Blocks.STONE.getDefaultState(), AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.STONE));
	
	// Nature Blocks
	public static final Block salsola_seeds = new BlockSalsolaSeeds();
	public static final Block rubber_log = new BlockRubberLog("rubber_log", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block rubber_wood = new BlockRubberLog("rubber_wood", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block rubber_leaves = new BlockLeavesBase("rubber_leaves", Material.LEAVES, 0.2F, 0.2F, SoundType.PLANT);
	public static final Block rubber_sapling = new BlockSaplingBase("rubber_sapling", new ResourceLocation(Industria.MODID, "nature/rubber_tree"));
	public static final Block marple_log = new BlockLogBase("marple_log", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block marple_wood = new BlockLogBase("marple_wood", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block marple_leaves = new BlockMarpleLeaves();
	public static final Block marple_leaves_red = new BlockLeavesBase("marple_leaves_red", Material.LEAVES, 0.2F, 0.2F, SoundType.PLANT);
	public static final Block mangrove_log = new BlockLogBase("mangrove_log", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block mangrove_wood = new BlockLogBase("mangrove_wood", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block mangrove_leaves = new BlockLeavesBase("mangrove_leaves", Material.LEAVES, 0.2F, 0.2F, SoundType.PLANT);
	public static final Block beech_log = new BlockLogBase("beech_log", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block beech_wood = new BlockLogBase("beech_wood", Material.WOOD, 2F, SoundType.WOOD);
	public static final Block beech_leaves = new BlockLeavesBase("beech_leaves", Material.LEAVES, 0.2F, 0.2F, SoundType.PLANT);
	public static final Block swamp_algae = new BlockSwampAlgae();
	public static final Block hanging_vine = new BlockHangingVine();
	
	// Util Blocks
	public static final Block reinforced_casing = new BlockReinforcedCasing();
	public static final Block ender_core = new BlockEnderCore();
	public static final Block ash = new BlockFallingDust("ash");
	
	// Fluids and Buckets
	public static final Block steam = new BlockSteam();
	public static final Item steam_bucket = new ItemGasBucket(ModFluids.STEAM, "steam_bucket", Industria.MATERIALS);
	public static final Block destilled_water = new BlockDestilledWater();
	public static final Item destilled_water_bucket = new ItemFluidBucket(ModFluids.DESTILLED_WATER, "destilled_water_bucket", Industria.MATERIALS);
	public static final Block sulfuric_acid = new BlockSulfuricAcid();
	public static final Item sulfuric_acid_bucket = new ItemFluidBucket(ModFluids.SULFURIC_ACID, "sulfuric_acid_bucket", Industria.MATERIALS);
	public static final Block natron_lye = new BlockNatronLye();
	public static final Item natron_lye_bucket = new ItemFluidBucket(ModFluids.NATRON_LYE, "natron_lye_bucket", Industria.MATERIALS);
	public static final Block chemical_water = new BlockChemicalWater();
	public static final Item chemical_water_bucket = new ItemFluidBucket(ModFluids.CHEMICAL_WATER, "chemical_water_bucket", Industria.MATERIALS);
	public static final Block iron_solution = new BlockOreSolution("iron_solution", ModFluids.IRON_SOLUTION);
	public static final Item iron_solution_bucket = new ItemFluidBucket(ModFluids.IRON_SOLUTION, "iron_solution_bucket", Industria.MATERIALS);
	public static final Block copper_solution = new BlockOreSolution("copper_solution", ModFluids.COPPER_SOLUTION);
	public static final Item copper_solution_bucket = new ItemFluidBucket(ModFluids.COPPER_SOLUTION, "copper_solution_bucket", Industria.MATERIALS);
	public static final Block aluminium_solution = new BlockOreSolution("aluminium_solution", ModFluids.ALUMINIUM_SOLUTION);
	public static final Item aluminium_solution_bucket = new ItemFluidBucket(ModFluids.ALUMINIUM_SOLUTION, "aluminium_solution_bucket", Industria.MATERIALS);
	public static final Block wolfram_solution = new BlockOreSolution("wolfram_solution", ModFluids.WOLFRAM_SOLUTION);
	public static final Item wolfram_solution_bucket = new ItemFluidBucket(ModFluids.WOLFRAM_SOLUTION, "wolfram_solution_bucket", Industria.MATERIALS);
	public static final Block tin_solution = new BlockOreSolution("tin_solution", ModFluids.TIN_SOLUTION);
	public static final Item tin_solution_bucket = new ItemFluidBucket(ModFluids.TIN_SOLUTION, "tin_solution_bucket", Industria.MATERIALS);
	public static final Block raw_oil = new BlockRawOil();
	public static final Item raw_oil_bucket = new ItemFluidBucket(ModFluids.RAW_OIL, "raw_oil_bucket", Industria.MATERIALS);
	public static final Block compressed_air = new BlockCompressedAir();
	public static final Item compressed_air_bucket = new ItemGasBucket(ModFluids.COMPRESSED_AIR, "compressed_air_bucket", Industria.MATERIALS);
	
	// Ingots and Nuggets
	public static final Item monel_ingot = new ItemBase("monel_ingot", Industria.MATERIALS);
	public static final Item tin_ingot = new ItemBase("tin_ingot", Industria.MATERIALS);
	public static final Item silver_ingot = new ItemBase("silver_ingot", Industria.MATERIALS);
	public static final Item palladium_ingot = new ItemBase("palladium_ingot", Industria.MATERIALS);
	public static final Item wolfram_ingot = new ItemBase("wolfram_ingot", Industria.MATERIALS);
	public static final Item nickel_ingot = new ItemBase("nickel_ingot", Industria.MATERIALS);
	public static final Item copper_ingot = new ItemBase("copper_ingot", Industria.MATERIALS);
	public static final Item electrolyt_copper_ingot = new ItemBase("electrolyt_copper_ingot", Industria.MATERIALS);
	public static final Item aluminium_ingot = new ItemBase("aluminium_ingot", Industria.MATERIALS);
	public static final Item steel_ingot = new ItemBase("steel_ingot", Industria.MATERIALS);
	public static final Item redstone_ingot = new ItemBase("redstone_ingot", Industria.MATERIALS);
	public static final Item monel_nugget = new ItemBase("monel_nugget", Industria.MATERIALS);
	public static final Item tin_nugget = new ItemBase("tin_nugget", Industria.MATERIALS);
	public static final Item silver_nugget = new ItemBase("silver_nugget", Industria.MATERIALS);
	public static final Item palladium_nugget = new ItemBase("palladium_nugget", Industria.MATERIALS);
	public static final Item wolfram_nugget = new ItemBase("wolfram_nugget", Industria.MATERIALS);
	public static final Item nickel_nugget = new ItemBase("nickel_nugget", Industria.MATERIALS);
	public static final Item copper_nugget = new ItemBase("copper_nugget", Industria.MATERIALS);
	public static final Item electrolyt_copper_nugget = new ItemBase("electrolyt_copper_nugget", Industria.MATERIALS);
	public static final Item aluminium_nugget = new ItemBase("aluminium_nugget", Industria.MATERIALS);
	public static final Item steel_nugget = new ItemBase("steel_nugget", Industria.MATERIALS);
	public static final Item redstone_nugget = new ItemBase("redstone_nugget", Industria.MATERIALS);
	public static final Item monel_dust = new ItemBase("monel_dust", Industria.MATERIALS);
	public static final Item tin_dust = new ItemBase("tin_dust", Industria.MATERIALS);
	public static final Item silver_dust = new ItemBase("silver_dust", Industria.MATERIALS);
	public static final Item palladium_dust = new ItemBase("palladium_dust", Industria.MATERIALS);
	public static final Item wolfram_dust = new ItemBase("wolfram_dust", Industria.MATERIALS);
	public static final Item nickel_dust = new ItemBase("nickel_dust", Industria.MATERIALS);
	public static final Item copper_dust = new ItemBase("copper_dust", Industria.MATERIALS);
	public static final Item electrolyt_copper_dust = new ItemBase("electrolyt_copper_dust", Industria.MATERIALS);
	public static final Item aluminium_dust = new ItemBase("aluminium_dust", Industria.MATERIALS);
	public static final Item steel_dust = new ItemBase("steel_dust", Industria.MATERIALS);
	public static final Item redstone_alloy_dust = new ItemBase("redstone_alloy_dust", Industria.MATERIALS);
	public static final Item iron_dust = new ItemBase("iron_dust", Industria.MATERIALS);
	public static final Item gold_dust = new ItemBase("gold_dust", Industria.MATERIALS);
	public static final Item tpo_iron_dust = new ItemBase("tpo_iron_dust", Industria.MATERIALS);
	public static final Item tpo_gold_dust = new ItemBase("tpo_gold_dust", Industria.MATERIALS);
	public static final Item tpo_monel_dust = new ItemBase("tpo_monel_dust", Industria.MATERIALS);
	public static final Item tpo_tin_dust = new ItemBase("tpo_tin_dust", Industria.MATERIALS);
	public static final Item tpo_silver_dust = new ItemBase("tpo_silver_dust", Industria.MATERIALS);
	public static final Item tpo_palladium_dust = new ItemBase("tpo_palladium_dust", Industria.MATERIALS);
	public static final Item tpo_wolfram_dust = new ItemBase("tpo_wolfram_dust", Industria.MATERIALS);
	public static final Item tpo_nickel_dust = new ItemBase("tpo_nickel_dust", Industria.MATERIALS);
	public static final Item tpo_copper_dust = new ItemBase("tpo_copper_dust", Industria.MATERIALS);
	public static final Item tpo_electrolyt_copper_dust = new ItemBase("tpo_electrolyt_copper_dust", Industria.MATERIALS);
	public static final Item tpo_aluminium_dust = new ItemBase("tpo_aluminium_dust", Industria.MATERIALS);
	public static final Item tpo_steel_dust = new ItemBase("tpo_steel_dust", Industria.MATERIALS);
	public static final Item tpo_redstone_alloy_dust = new ItemBase("tpo_redstone_alloy_dust", Industria.MATERIALS);
	public static final Item monel_plate = new ItemBase("monel_plate", Industria.MATERIALS);
	public static final Item tin_plate = new ItemBase("tin_plate", Industria.MATERIALS);
	public static final Item silver_plate = new ItemBase("silver_plate", Industria.MATERIALS);
	public static final Item palladium_plate = new ItemBase("palladium_plate", Industria.MATERIALS);
	public static final Item wolfram_plate = new ItemBase("wolfram_plate", Industria.MATERIALS);
	public static final Item nickel_plate = new ItemBase("nickel_plate", Industria.MATERIALS);
	public static final Item copper_plate = new ItemBase("copper_plate", Industria.MATERIALS);
	public static final Item electrolyt_copper_plate = new ItemBase("electrolyt_copper_plate", Industria.MATERIALS);
	public static final Item aluminium_plate = new ItemBase("aluminium_plate", Industria.MATERIALS);
	public static final Item steel_plate = new ItemBase("steel_plate", Industria.MATERIALS);
	public static final Item redstone_alloy_plate = new ItemBase("redstone_alloy_plate", Industria.MATERIALS);
	public static final Item iron_plate = new ItemBase("iron_plate", Industria.MATERIALS);
	public static final Item gold_plate = new ItemBase("gold_plate", Industria.MATERIALS);
	public static final Item netherite_plate = new ItemBase("netherite_plate", Industria.MATERIALS);
	
	// Resource Items
	public static final Item salsola = new ItemSalsola();
	public static final Item crushed_stone = new ItemBase("crushed_stone", Industria.MATERIALS);
	public static final Item crushed_blackstone = new ItemBase("crushed_blackstone", Industria.MATERIALS);
	public static final Item crushed_netherrack = new ItemBase("crushed_netherrack", Industria.MATERIALS);
	public static final Item crushed_bauxite = new ItemBase("crushed_bauxite", Industria.MATERIALS);
	public static final Item crushed_wolframite = new ItemBase("crushed_wolframite", Industria.MATERIALS);
	public static final Item crushed_iron_ore = new ItemBase("crushed_iron_ore", Industria.MATERIALS);
	public static final Item crushed_copper_ore = new ItemBase("crushed_copper_ore", Industria.MATERIALS);
	public static final Item crushed_gold_ore = new ItemBase("crushed_gold_ore", Industria.MATERIALS);
	public static final Item crushed_tin_ore = new ItemBase("crushed_tin_ore", Industria.MATERIALS);
	public static final Item crushed_silver_ore = new ItemBase("crushed_silver_ore", Industria.MATERIALS);
	public static final Item crushed_palladium_ore = new ItemBase("crushed_palladium_ore", Industria.MATERIALS);
	public static final Item crushed_nickel_ore = new ItemBase("crushed_nickel_ore", Industria.MATERIALS);
	public static final Item iron_oxid = new ItemBase("iron_oxid", Industria.MATERIALS);
	public static final Item copper_oxid = new ItemBase("copper_oxid", Industria.MATERIALS);
	public static final Item tin_oxid = new ItemBase("tin_oxid", Industria.MATERIALS);
	public static final Item pure_gold = new ItemBase("pure_gold", Industria.MATERIALS);
	public static final Item pure_silver = new ItemBase("pure_silver", Industria.MATERIALS);
	public static final Item pure_palladium = new ItemBase("pure_palladium", Industria.MATERIALS);
	public static final Item pure_nickel = new ItemBase("pure_nickel", Industria.MATERIALS);
	public static final Item pure_tin_ore = new ItemBase("pure_tin_ore", Industria.MATERIALS);
	public static final Item pure_iron_ore = new ItemBase("pure_iron_ore", Industria.MATERIALS);
	public static final Item pure_copper_ore = new ItemBase("pure_copper_ore", Industria.MATERIALS);
	public static final Item pure_gold_ore = new ItemBase("pure_gold_ore", Industria.MATERIALS);
	public static final Item pure_silver_ore = new ItemBase("pure_silver_ore", Industria.MATERIALS);
	public static final Item pure_palladium_ore = new ItemBase("pure_palladium_ore", Industria.MATERIALS);
	public static final Item pure_nickel_ore = new ItemBase("pure_nickel_ore", Industria.MATERIALS);
	public static final Item sulfur = new ItemBase("sulfur", Industria.MATERIALS);
	public static final Item crude_steel = new ItemBase("crude_steel", Industria.MATERIALS);
	public static final Item lime = new ItemBase("lime", Industria.MATERIALS);
	
	// Crafting items
	public static final Item bearing = new ItemBase("bearing", Industria.MATERIALS);
	public static final Item spring = new ItemBase("spring", Industria.MATERIALS);
	public static final Item led = new ItemBase("led", Industria.MATERIALS);
	public static final Item turbin = new ItemBase("turbin", Industria.MATERIALS);
	public static final Item condensator = new ItemBase("condensator", Industria.MATERIALS);
	public static final Item resistor = new ItemBase("resistor", Industria.MATERIALS);
	public static final Item rotor = new ItemBase("rotor", Industria.MATERIALS);
	public static final Item motor_coil = new ItemBase("motor_coil", Industria.MATERIALS);
	public static final Item copper_wire = new ItemBase("copper_wire", Industria.MATERIALS);
	public static final Item electrolyt_copper_wire = new ItemBase("electrolyt_copper_wire", Industria.MATERIALS);
	public static final Item aluminium_wire = new ItemBase("aluminium_wire", Industria.MATERIALS);
	public static final Item rubber = new ItemBase("rubber", Industria.MATERIALS);
	public static final Item plastic_pellets = new ItemBase("plastic_pellets", Industria.MATERIALS);
	public static final Item plastic_plate = new ItemBase("plastic_plate", Industria.MATERIALS);
	public static final Item polymer_resin = new ItemBase("polymer_resin", Industria.MATERIALS);
	public static final Item coal_coke = new ItemBase("coal_coke", Industria.MATERIALS);
	public static final Item silicon = new ItemBase("silicon", Industria.MATERIALS);
	public static final Item electrolyt_paper = new ItemBase("electrolyt_paper", Industria.MATERIALS);
	public static final Item salt = new ItemBase("salt", Industria.MATERIALS);
	public static final Item natrium = new ItemBase("natrium", Industria.MATERIALS);
	public static final Item raw_rubber_bottle = new ItemBase("raw_rubber_bottle", Industria.MATERIALS, 16);
	public static final Item rubber_bottle = new ItemBase("rubber_bottle", Industria.MATERIALS, 16, Items.GLASS_BOTTLE);
	public static final Item cardboard_sheet = new ItemBurneable("cardboard_sheet", Industria.MATERIALS, 64);
	
	// Functional Items
	public static final Item remote_control = new ItemRemoteControll();
	public static final Item iron_processor = new ItemProcessor("iron_processor", 4, false, Rarity.UNCOMMON);
	public static final Item redstone_processor = new ItemProcessor("redstone_processor", 7, false, Rarity.UNCOMMON);
	public static final Item emerald_processor = new ItemProcessor("emerald_processor", 10, false, Rarity.RARE);
	public static final Item netherite_processor = new ItemProcessor("netherite_processor", 14, true, Rarity.EPIC);
	public static final Item empty_blueprint = new ItemEmptyBlueprint();
	public static final Item blueprint = new ItemBlueprint();
	public static final Item lever_element = new ItemLeverElement();
	public static final Item button_element = new ItemButtonElement();
	public static final Item lamp_element = new ItemLampElement();
	public static final Item fuse_elv = new ItemFuse("fuse_elv", 8);
	public static final Item fuse_lv = new ItemFuse("fuse_lv", 16);
	public static final Item fuse_nv = new ItemFuse("fuse_nv", 32);
	public static final Item fuse_hv = new ItemFuse("fuse_hv", 64);
	public static final Item schredder_crusher = new ItemSchredderToolCrusher();
	public static final Item hard_drive = new ItemHardDrive();
	public static final Item structure_cladding_pane = new ItemStructureCladdingPane();
	
	// Tools
	public static final Item fluid_meter = new ItemFluidMeter();
	public static final Item energy_meter = new ItemEnergyMeter();
	public static final Item hammer = new ItemHammer();
	public static final Item cutter = new ItemCutter();
	public static final Block tree_tap = new BlockTreeTap();
	public static final Item network_configurtor = new ItemNetworkConfigurator();
		
}
