package de.industria;

import java.util.Optional;

import de.industria.packet.CCRecipeCreator;
import de.industria.packet.CConfigureNetworkDevice;
import de.industria.packet.CEditComputerCode;
import de.industria.packet.CEditJigsawTileEntityPacket;
import de.industria.packet.CEditProcessorCodePacket;
import de.industria.packet.CGenerateJigsaw;
import de.industria.packet.CRequestBlockEntityUpdates;
import de.industria.packet.CUpdateChunkLoader;
import de.industria.packet.SSendENHandeler;
import de.industria.packet.SUpdateBlockEntitys;
import de.industria.typeregistys.ModConfiguredFeatures;
import de.industria.typeregistys.ModItems;
import de.industria.typeregistys.ModTabs;
import de.industria.util.handler.ModGameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.DispenserBlock;
import net.minecraft.block.FlowingFluidBlock;
import net.minecraft.dispenser.IBlockSource;
import net.minecraft.dispenser.IDispenseItemBehavior;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.item.Rarity;
import net.minecraft.state.properties.BlockStateProperties;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.registry.Registry;
import net.minecraft.world.biome.Biome.Category;
import net.minecraft.world.biome.Biomes;
import net.minecraft.world.gen.GenerationStage.Decoration;
import net.minecraft.world.gen.feature.Features;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.network.NetworkDirection;
import net.minecraftforge.registries.IForgeRegistry;

@EventBusSubscriber(modid=Industria.MODID, bus=Mod.EventBusSubscriber.Bus.MOD)
public class ServerSetup {
	
	@SubscribeEvent
	@SuppressWarnings("deprecation")
	public static void setup(final FMLCommonSetupEvent event) {
		
		// Dispenser Behaviors
		IDispenseItemBehavior placeBlockBehavior = new IDispenseItemBehavior() {
			@Override
			public ItemStack dispense(IBlockSource source, ItemStack stack) {
				BlockPos pos = source.getPos().relative(source.getBlockState().getValue(BlockStateProperties.FACING));
				Block block = Block.byItem(stack.getItem());
				if (block != null && (source.getLevel().getBlockState(pos).isAir() || source.getLevel().getBlockState(pos).getBlock() instanceof FlowingFluidBlock) && block.canSurvive(block.defaultBlockState(), source.getLevel(), pos)) {
					source.getLevel().setBlockAndUpdate(pos, block.defaultBlockState());
					stack.shrink(1);
					return stack;
				}
				return stack;
			}
		};
		Registry.BLOCK.stream().forEach((block) -> {
			Item item = Item.byBlock(block);
			if (item != null) {
				if (item != Items.TNT) DispenserBlock.registerBehavior(item, placeBlockBehavior);
			}
		});

		// Vanilla FireInfo Overrides
//		MethodHelper.addFireSetting(Blocks.ACACIA_DOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.OAK_DOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.BIRCH_DOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.DARK_OAK_DOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.SPRUCE_DOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.CHEST, 5, 20);
//		MethodHelper.addFireSetting(Blocks.TRAPPED_CHEST, 5, 20);
//		MethodHelper.addFireSetting(Blocks.OAK_TRAPDOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.BIRCH_TRAPDOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.ACACIA_TRAPDOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.DARK_OAK_TRAPDOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.SPRUCE_TRAPDOOR, 5, 20);
//		MethodHelper.addFireSetting(Blocks.OAK_SIGN, 10, 30);
//		MethodHelper.addFireSetting(Blocks.BIRCH_SIGN, 10, 30);
//		MethodHelper.addFireSetting(Blocks.ACACIA_SIGN, 10, 30);
//		MethodHelper.addFireSetting(Blocks.DARK_OAK_SIGN, 10, 30);
//		MethodHelper.addFireSetting(Blocks.SPRUCE_SIGN, 10, 30);
//		MethodHelper.addFireSetting(Blocks.OAK_PRESSURE_PLATE, 10, 30);
//		MethodHelper.addFireSetting(Blocks.BIRCH_PRESSURE_PLATE, 10, 30);
//		MethodHelper.addFireSetting(Blocks.ACACIA_PRESSURE_PLATE, 10, 30);
//		MethodHelper.addFireSetting(Blocks.DARK_OAK_PRESSURE_PLATE, 10, 30);
//		MethodHelper.addFireSetting(Blocks.SPRUCE_PRESSURE_PLATE, 10, 30);
				
	}

	public static void constructMod() {

		// Register Packets
		Industria.NETWORK.registerMessage(0, CEditProcessorCodePacket.class, CEditProcessorCodePacket::encode, CEditProcessorCodePacket::new, CEditProcessorCodePacket::handle, Optional.of(NetworkDirection.PLAY_TO_SERVER));
		Industria.NETWORK.registerMessage(1, CEditJigsawTileEntityPacket.class, CEditJigsawTileEntityPacket::encode, CEditJigsawTileEntityPacket::new, CEditJigsawTileEntityPacket::handle, Optional.of(NetworkDirection.PLAY_TO_SERVER));
		Industria.NETWORK.registerMessage(2, CGenerateJigsaw.class, CGenerateJigsaw::encode, CGenerateJigsaw::new, CGenerateJigsaw::handle, Optional.of(NetworkDirection.PLAY_TO_SERVER));
		Industria.NETWORK.registerMessage(3, SSendENHandeler.class, SSendENHandeler::encode, SSendENHandeler::new, SSendENHandeler::handle, Optional.of(NetworkDirection.PLAY_TO_CLIENT));		
		Industria.NETWORK.registerMessage(4, CEditComputerCode.class, CEditComputerCode::encode, CEditComputerCode::new, CEditComputerCode::handle, Optional.of(NetworkDirection.PLAY_TO_SERVER));
		Industria.NETWORK.registerMessage(5, CConfigureNetworkDevice.class, CConfigureNetworkDevice::encode, CConfigureNetworkDevice::new, CConfigureNetworkDevice::handle, Optional.of(NetworkDirection.PLAY_TO_SERVER));
		Industria.NETWORK.registerMessage(6, CUpdateChunkLoader.class, CUpdateChunkLoader::encode, CUpdateChunkLoader::new, CUpdateChunkLoader::handle);
		Industria.NETWORK.registerMessage(7, CCRecipeCreator.class, CCRecipeCreator::encode, CCRecipeCreator::new, CCRecipeCreator::handle);
		Industria.NETWORK.registerMessage(8, SUpdateBlockEntitys.class, SUpdateBlockEntitys::encode, SUpdateBlockEntitys::new, SUpdateBlockEntitys::handle);
		Industria.NETWORK.registerMessage(9, CRequestBlockEntityUpdates.class, CRequestBlockEntityUpdates::encode, CRequestBlockEntityUpdates::new, CRequestBlockEntityUpdates::handle);
		
		// Devstuff
		ModGameRegistry.registerBlock(ModItems.recipe_creator, ModTabs.TOOLS);
		
		// register Blocks
		ModGameRegistry.registerBlock(ModItems.iron_machine_casing, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.steel_machine_casing, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_machine_casing, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.metal_glass_machine_casing, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.aluminium_machine_casing, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tree_tap, ModTabs.TOOLS);
		ModGameRegistry.registerBlock(ModItems.redstone_capacitor, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.pulse_counter, ItemGroup.TAB_REDSTONE); 
		ModGameRegistry.registerBlock(ModItems.stacked_redstone_torch, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.stacked_redstone_wire, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.advanced_piston, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.advanced_sticky_piston, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerTechnicalBlock(ModItems.advanced_piston_head);
		ModGameRegistry.registerTechnicalBlock(ModItems.advanced_moving_block);
		ModGameRegistry.registerBlock(ModItems.redstone_reciver, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.signal_wire, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.antenna_conector, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.linear_conector, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.storing_crafting_table, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.signal_processor_contact, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.rail_piston, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.conector_block, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.redstone_contact, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.button_block, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.radial_conector, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.hover_controler, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.hover_extension, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.controll_panel, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.harvester, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.copper_cable, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.electrolyt_copper_cable, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.aluminium_cable, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.burned_cable, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.infinity_power_source, null);
		ModGameRegistry.registerBlock(ModItems.panel_lamp, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.floodlight, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.steel_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.aluminium_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.electrolyt_copper_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.redstone_alloy_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lead_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tin_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.vanadium_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.silver_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolfram_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.nickel_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.monel_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.zirconium_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tin_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.silver_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.nickel_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.iron_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.zirconium_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gold_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.steel_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.aluminium_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.electrolyt_copper_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.redstone_alloy_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.silver_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.vanadium_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lead_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tin_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolfram_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.nickel_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.monel_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.netherite_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.iron_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.zirconium_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gold_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.steel_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.aluminium_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.electrolyt_copper_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.redstone_alloy_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.silver_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.vanadium_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lead_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tin_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolfram_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.nickel_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.monel_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.netherite_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.sulfur_ore, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.reinforced_casing, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.ender_core, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.preassure_pipe, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.rubber_log, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.rubber_wood, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.rubber_leaves, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.rubber_sapling, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.marple_log, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.marple_wood, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.marple_leaves, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.marple_leaves_red, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.swamp_algae, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.hanging_vine, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.flax_crop, ModTabs.MATERIALS);
		ModGameRegistry.registerBlock(ModItems.metallic_glass_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.metallic_glass_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.metallic_glass_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.motor, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.cement_bag, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.smooth_cobblestone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.chiseled_smooth_stone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.iron_rod, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.stone_corner, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salsola_seeds, ModTabs.MATERIALS);
		ModGameRegistry.registerBlock(ModItems.jigsaw, null, Rarity.EPIC);
		ModGameRegistry.registerBlock(ModItems.battery, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.generator, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.diode, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.capacitor_bank, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.steel_pipe, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.copper_pipe, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.metallic_glass_pipe, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.fluid_valve, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.fluid_input, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.fluid_output, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.steam_generator, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.coal_heater, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.electric_heater, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.gas_heater, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.transformator_coil, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.transformator_contact, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.fuse_box, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.multimeter, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.power_switch, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.electric_furnace, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.schredder, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.blender, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.raffinery, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.alloy_furnace, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.conveyor_belt, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.conveyor_spliter, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.conveyor_switch, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.thermal_zentrifuge, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.fluid_bath, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.blast_furnace, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.metal_former, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.pipe_preassurizer, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.air_compressor, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.item_distributor, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.preassure_pipe_item_terminal, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.ore_washing_plant, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.cardboard_box, ModTabs.DECORATIONS);
		ModGameRegistry.registerTechnicalBlock(ModItems.energy_barrier);
		ModGameRegistry.registerBlock(ModItems.energy_barrier_border, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.energy_barrier_generator, ModTabs.MACHINES);
		
		ModGameRegistry.registerBlock(ModItems.mangrove_log, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.mangrove_wood, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.mangrove_leaves, ModTabs.DECORATIONS);
		
		ModGameRegistry.registerBlock(ModItems.beech_log, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.beech_wood, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.beech_leaves, ModTabs.DECORATIONS);
		
		ModGameRegistry.registerBlock(ModItems.salt_sand, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.mossy_end_stone_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_nether_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_red_sandstone_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_sandstone_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salt_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blue_nether_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_red_nether_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_prismarine_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_quartz_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_end_stone_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_red_sandstone_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_sandstone_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_salt_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_quartz_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_diorite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_granite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_andesite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_stone_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.chiseled_blue_nether_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.chiseled_red_nether_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_diorite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_granite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_bauxite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_dark_prismarine, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_prismarine, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_end_stone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_red_sandstone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_sandstone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_stone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blackstone_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.quartz_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.diorite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.granite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.andesite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.stone_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_tiles, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salt_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_andesite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_diorite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_granite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_wolframite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_bauxite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_andesite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_diorite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_granite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_wolframite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_polished_bauxite_bricks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_andesite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_wolframite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.concrete, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.concrete_sheet, ModTabs.DECORATIONS);
		
		ModGameRegistry.registerBlock(ModItems.concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_dark_prismarine_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_prismarine_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_end_stone_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_red_sandstone_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_sandstone_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_stone_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_bauxite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_wolframite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blackstone_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.quartz_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.diorite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.granite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.andesite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.stone_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_quartz_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_diorite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_granite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_andesite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_stone_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_tiles_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_nether_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.quartz_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_sandstone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.sandstone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.diorite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.granite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.andesite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salt_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_diorite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_granite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_andesite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_bauxite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_wolframite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.mossy_end_stone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_stained_glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.glass_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.netherrack_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.end_stone_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salt_slab, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.cracked_red_nether_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blue_nether_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_andesite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_diorite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_granite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_sandstone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_red_sandstone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_nether_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_stone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_prismarine_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_end_stone_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_quartz_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_salt_brick_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.iron_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gold_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.steel_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.aluminium_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.electrolyt_copper_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.redstone_alloy_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.silver_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.vanadium_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lead_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tin_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolfram_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.nickel_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.monel_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.netherite_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_copper_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_tin_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_iron_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_steel_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_copper_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_tin_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_iron_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_steel_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_copper_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_tin_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_iron_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_steel_planks_slab, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.lime_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_terracotta_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_painted_planks_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_concrete_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_concrete_slab, ModTabs.BUILDING_BLOCKS);
		
//		ModGameRegistry.registerBlock(ModItems.cracked_warped_wart_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_nether_wart_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_netherrack_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_prismarine_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_quartz_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_end_stone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_red_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_diorite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_granite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_andesite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_stone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_salt_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cut_red_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cut_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_warped_wart_slab, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_nether_wart_slab, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.white_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.white_stained_glass_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.glass_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.netherrack_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.terracotta_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.end_stone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.bauxite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.wolframite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.iron_plates_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.iron_planks_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.salt_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.white_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.burned_planks_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_dark_prismarine_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_prismarine_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_end_stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_red_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_diorite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_granite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_andesite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_bauxite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_wolframite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.mossy_end_stone_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.mossy_end_stone_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.purpur_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_quartz_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_basalt_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_red_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_diorite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_granite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_andesite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_bauxite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_wolframite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_quartz_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_diorite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_granite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_andesite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_stone_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.netherrack_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.dark_prismarine_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.terracotta_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.quartz_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.end_stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.bauxite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.wolframite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.iron_plates_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.iron_planks_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.salt_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.white_painted_planks_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.burned_planks_fence, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.blackstone_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.quartz_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.diorite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.granite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.andesite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.stone_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.bauxite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.wolframite_tiles_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cut_red_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cut_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.blue_nether_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.prismarine_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.quartz_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.red_sandstone_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.sandstone_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.diorite_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.granite_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.andesite_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.bauxite_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.wolframite_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.salt_brick_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_warped_wart_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_nether_wart_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_netherrack_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_prismarine_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_terracotta_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_quartz_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_end_stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_red_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_sandstone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_diorite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_granite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_andesite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_stone_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_salt_wall, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.blackstone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.quartz_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.diorite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.granite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.andesite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.stone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.bauxite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.wolframite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_basalt_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_diorite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_granite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_andesite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_bauxite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.smooth_wolframite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.blue_nether_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.quartz_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.red_sandstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.sandstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.diorite_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.granite_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.andesite_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.bauxite_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.wolframite_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.salt_brick_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_dark_prismarine_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_prismarine_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_end_stone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_red_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_stone_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_bauxite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.polished_wolframite_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_quartz_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_diorite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_granite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_andesite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_stone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
//		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_tiles_stairs, ModTabs.BUILDING_BLOCKS);

		
		
		
		
		ModGameRegistry.registerBlock(ModItems.exposed_copper_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_tin_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_iron_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_steel_plates, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.oxidized_copper_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_tin_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_iron_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_steel_plates, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.weathered_copper_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_tin_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_iron_plates, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_steel_plates, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.exposed_copper_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_tin_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_iron_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_steel_planks, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.oxidized_copper_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_tin_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_iron_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_steel_planks, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.weathered_copper_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_tin_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_iron_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_steel_planks, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.tar_crust, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.cardboard_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_wolframite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_bauxite, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_painted_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.limestone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.karstified_limestone, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.limestone_sheet, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.item_detector, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.lightbarrier, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.movement_detector, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.computer, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.network_cable, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.steel_rail, ItemGroup.TAB_TRANSPORTATION);
		ModGameRegistry.registerBlock(ModItems.inductive_rail, ItemGroup.TAB_TRANSPORTATION);
		ModGameRegistry.registerBlock(ModItems.rail_adapter, ItemGroup.TAB_TRANSPORTATION);
		ModGameRegistry.registerBlock(ModItems.chunk_loader, ModTabs.MACHINES);
		ModGameRegistry.registerBlock(ModItems.clean_cladding_black, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.clean_cladding_white, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.structure_scaffold, ItemGroup.TAB_REDSTONE);
		ModGameRegistry.registerBlock(ModItems.ash, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.biomass, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.burned_log, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.burned_planks, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.burned_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.burned_wood_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.burned_wood_slab, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.burned_trapdoor, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.burned_door, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.burned_fence, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.burned_scrap, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.bound_stick_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bound_bamboo_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bound_sugar_cane_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.raw_nickel_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.raw_vanadium_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.raw_quartz_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.raw_silver_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.raw_tin_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.dried_peat, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.peat, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.humus, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.sulfur_crust_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.fluorite_crystal, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.zircon_crystal, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.iron_ladder, ModTabs.DECORATIONS);
		ModGameRegistry.registerBlock(ModItems.sulfur_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.charcoal_block, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.crude_steel_block, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerBlock(ModItems.gold_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.aluminium_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.electrolyt_copper_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.redstone_alloy_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.silver_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.vanadium_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolfram_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.nickel_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.monel_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.netherite_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_copper_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_tin_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_iron_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.oxidized_steel_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_copper_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_tin_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_iron_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.weathered_steel_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_copper_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_tin_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_iron_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.exposed_steel_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lead_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.tin_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.steel_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.copper_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.iron_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.white_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.orange_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.magenta_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_blue_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.yellow_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.lime_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.pink_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.gray_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.light_gray_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cyan_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.purple_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.brown_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.green_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.black_painted_planks_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.concrete_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blue_nether_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_nether_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_red_nether_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_andesite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_diorite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_granite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_sandstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_red_sandstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_stone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_prismarine_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_quartz_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_end_stone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.netherrack_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.end_stone_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salt_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blue_nether_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.quartz_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.diorite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.granite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.andesite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.salt_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_salt_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.terracotta_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_red_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_sandstone_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_end_stone_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_prismarine_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_dark_prismarine_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_stone_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_bauxite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.polished_wolframite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.mossy_end_stone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.blackstone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.quartz_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.diorite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.granite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.andesite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.stone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.bauxite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.wolframite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_diorite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_granite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_andesite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_bauxite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.smooth_wolframite_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_blackstone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_quartz_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_diorite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_granite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_andesite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_stone_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_bauxite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.cracked_wolframite_tiles_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.red_sandstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		ModGameRegistry.registerBlock(ModItems.sandstone_brick_stairs, ModTabs.BUILDING_BLOCKS);
		
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_electric_copper_cable);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_electric_electrolyt_copper_cable);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_electric_aluminium_cable);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_electric_burned_cable);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_network_cable);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_steel_pipe);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_copper_pipe);
		ModGameRegistry.registerTechnicalBlock(ModItems.encased_metallic_glass_pipe);
		ModGameRegistry.registerTechnicalBlock(ModItems.luminous_air);
		
		ModGameRegistry.registerTechnicalBlock(ModItems.steam);
		ModGameRegistry.registerItem(ModItems.steam_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.destilled_water);
		ModGameRegistry.registerItem(ModItems.destilled_water_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.hydrofluoric_acid);
		ModGameRegistry.registerItem(ModItems.hydrofluoric_acid_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.sulfuric_acid);
		ModGameRegistry.registerItem(ModItems.sulfuric_acid_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.natron_lye);
		ModGameRegistry.registerItem(ModItems.natron_lye_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.raw_oil);
		ModGameRegistry.registerItem(ModItems.raw_oil_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.fuel_gas);
		ModGameRegistry.registerItem(ModItems.fuel_gas_bucket);
		
		ModGameRegistry.registerTechnicalBlock(ModItems.iron_solution);
		ModGameRegistry.registerItem(ModItems.iron_solution_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.copper_solution);
		ModGameRegistry.registerItem(ModItems.copper_solution_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.aluminium_solution);
		ModGameRegistry.registerItem(ModItems.aluminium_solution_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.wolfram_solution);
		ModGameRegistry.registerItem(ModItems.wolfram_solution_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.tin_solution);
		ModGameRegistry.registerItem(ModItems.tin_solution_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.vanadium_solution);
		ModGameRegistry.registerItem(ModItems.vanadium_solution_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.chemical_water);
		ModGameRegistry.registerItem(ModItems.chemical_water_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.compressed_air);
		ModGameRegistry.registerItem(ModItems.compressed_air_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.liquid_concrete);
		ModGameRegistry.registerItem(ModItems.liquid_concrete_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.biogas);
		ModGameRegistry.registerItem(ModItems.biogas_bucket);
		ModGameRegistry.registerTechnicalBlock(ModItems.tar);
		ModGameRegistry.registerItem(ModItems.tar_bucket);
		
		ModGameRegistry.registerTechnicalBlock(ModItems.fluid_cannister.getBlock());
		ModGameRegistry.registerItem(ModItems.fluid_cannister);
		
		// register Items
		ModGameRegistry.registerItem(ModItems.paper_bag);
		ModGameRegistry.registerItem(ModItems.crushed_blackstone);
		ModGameRegistry.registerItem(ModItems.crushed_netherrack);
		ModGameRegistry.registerItem(ModItems.crushed_bauxite);
		ModGameRegistry.registerItem(ModItems.crushed_wolframite);
		ModGameRegistry.registerItem(ModItems.tin_oxid);
		ModGameRegistry.registerItem(ModItems.iron_oxid);
		ModGameRegistry.registerItem(ModItems.copper_oxid);
		ModGameRegistry.registerItem(ModItems.pure_gold);
		ModGameRegistry.registerItem(ModItems.pure_silver);
		ModGameRegistry.registerItem(ModItems.pure_vanadium);
		ModGameRegistry.registerItem(ModItems.pure_nickel);
		ModGameRegistry.registerItem(ModItems.crushed_tin_ore);
		ModGameRegistry.registerItem(ModItems.crushed_iron_ore);
		ModGameRegistry.registerItem(ModItems.crushed_copper_ore);
		ModGameRegistry.registerItem(ModItems.crushed_nickel_ore);
		ModGameRegistry.registerItem(ModItems.crushed_gold_ore);
		ModGameRegistry.registerItem(ModItems.crushed_silver_ore);
		ModGameRegistry.registerItem(ModItems.pure_tin_ore);
		ModGameRegistry.registerItem(ModItems.pure_iron_ore);
		ModGameRegistry.registerItem(ModItems.pure_copper_ore);
		ModGameRegistry.registerItem(ModItems.pure_nickel_ore);
		ModGameRegistry.registerItem(ModItems.pure_gold_ore);
		ModGameRegistry.registerItem(ModItems.pure_silver_ore);
		ModGameRegistry.registerItem(ModItems.crushed_stone);
		ModGameRegistry.registerItem(ModItems.redstone_ingot);
		ModGameRegistry.registerItem(ModItems.remote_control);
		ModGameRegistry.registerItem(ModItems.iron_processor);
		ModGameRegistry.registerItem(ModItems.redstone_processor);
		ModGameRegistry.registerItem(ModItems.emerald_processor);
		ModGameRegistry.registerItem(ModItems.netherite_processor);
		ModGameRegistry.registerItem(ModItems.salsola);
		ModGameRegistry.registerItem(ModItems.empty_blueprint);
		ModGameRegistry.registerItem(ModItems.blueprint);
		ModGameRegistry.registerItem(ModItems.copper_ingot);
		ModGameRegistry.registerItem(ModItems.copper_nugget);
		ModGameRegistry.registerItem(ModItems.electrolyt_copper_ingot);
		ModGameRegistry.registerItem(ModItems.electrolyt_copper_nugget);
		ModGameRegistry.registerItem(ModItems.steel_ingot);
		ModGameRegistry.registerItem(ModItems.steel_nugget);
		ModGameRegistry.registerItem(ModItems.aluminium_ingot);
		ModGameRegistry.registerItem(ModItems.aluminium_nugget);
		ModGameRegistry.registerItem(ModItems.redstone_nugget);
		ModGameRegistry.registerItem(ModItems.lead_ingot);
		ModGameRegistry.registerItem(ModItems.lead_nugget);
		ModGameRegistry.registerItem(ModItems.lead_dust);
		ModGameRegistry.registerItem(ModItems.tpo_lead_dust);
		ModGameRegistry.registerItem(ModItems.lead_plate);
		ModGameRegistry.registerItem(ModItems.tin_ingot);
		ModGameRegistry.registerItem(ModItems.tin_nugget);
		ModGameRegistry.registerItem(ModItems.wolfram_ingot);
		ModGameRegistry.registerItem(ModItems.wolfram_nugget);
		ModGameRegistry.registerItem(ModItems.silver_ingot);
		ModGameRegistry.registerItem(ModItems.silver_nugget);
		ModGameRegistry.registerItem(ModItems.vanadium_ingot);
		ModGameRegistry.registerItem(ModItems.vanadium_nugget);
		ModGameRegistry.registerItem(ModItems.nickel_ingot);
		ModGameRegistry.registerItem(ModItems.nickel_nugget);
		ModGameRegistry.registerItem(ModItems.monel_ingot);
		ModGameRegistry.registerItem(ModItems.monel_nugget);
		ModGameRegistry.registerItem(ModItems.tpo_copper_dust);
		ModGameRegistry.registerItem(ModItems.copper_dust);
		ModGameRegistry.registerItem(ModItems.electrolyt_copper_dust);
		ModGameRegistry.registerItem(ModItems.tpo_electrolyt_copper_dust);
		ModGameRegistry.registerItem(ModItems.steel_dust);
		ModGameRegistry.registerItem(ModItems.tpo_steel_dust);
		ModGameRegistry.registerItem(ModItems.aluminium_dust);
		ModGameRegistry.registerItem(ModItems.tpo_aluminium_dust);
		ModGameRegistry.registerItem(ModItems.redstone_alloy_dust);
		ModGameRegistry.registerItem(ModItems.tpo_redstone_alloy_dust);
		ModGameRegistry.registerItem(ModItems.tin_dust);
		ModGameRegistry.registerItem(ModItems.tpo_tin_dust);
		ModGameRegistry.registerItem(ModItems.wolfram_dust);
		ModGameRegistry.registerItem(ModItems.tpo_wolfram_dust);
		ModGameRegistry.registerItem(ModItems.silver_dust);
		ModGameRegistry.registerItem(ModItems.tpo_silver_dust);
		ModGameRegistry.registerItem(ModItems.vanadium_dust);
		ModGameRegistry.registerItem(ModItems.tpo_vanadium_dust);
		ModGameRegistry.registerItem(ModItems.nickel_dust);
		ModGameRegistry.registerItem(ModItems.tpo_nickel_dust);
		ModGameRegistry.registerItem(ModItems.monel_dust);
		ModGameRegistry.registerItem(ModItems.tpo_monel_dust);
		ModGameRegistry.registerItem(ModItems.iron_dust);
		ModGameRegistry.registerItem(ModItems.tpo_iron_dust);
		ModGameRegistry.registerItem(ModItems.gold_dust);
		ModGameRegistry.registerItem(ModItems.tpo_gold_dust);
		ModGameRegistry.registerItem(ModItems.copper_plate);
		ModGameRegistry.registerItem(ModItems.electrolyt_copper_plate);
		ModGameRegistry.registerItem(ModItems.steel_plate);
		ModGameRegistry.registerItem(ModItems.aluminium_plate);
		ModGameRegistry.registerItem(ModItems.redstone_alloy_plate);
		ModGameRegistry.registerItem(ModItems.tin_plate);
		ModGameRegistry.registerItem(ModItems.wolfram_plate);
		ModGameRegistry.registerItem(ModItems.silver_plate);
		ModGameRegistry.registerItem(ModItems.vanadium_plate);
		ModGameRegistry.registerItem(ModItems.nickel_plate);
		ModGameRegistry.registerItem(ModItems.monel_plate);
		ModGameRegistry.registerItem(ModItems.gold_plate);
		ModGameRegistry.registerItem(ModItems.iron_plate);
		ModGameRegistry.registerItem(ModItems.netherite_plate);
		ModGameRegistry.registerItem(ModItems.hammer);
		ModGameRegistry.registerItem(ModItems.cutter);
		ModGameRegistry.registerItem(ModItems.wrench);
		ModGameRegistry.registerItem(ModItems.brush);
		ModGameRegistry.registerItem(ModItems.aluminium_wire);
		ModGameRegistry.registerItem(ModItems.copper_wire);
		ModGameRegistry.registerItem(ModItems.electrolyt_copper_wire);
		ModGameRegistry.registerItem(ModItems.rotor);
		ModGameRegistry.registerItem(ModItems.motor_coil);
		ModGameRegistry.registerItem(ModItems.plastic_pellets);
		ModGameRegistry.registerItem(ModItems.polymer_resin);
		ModGameRegistry.registerItem(ModItems.rubber);
		ModGameRegistry.registerItem(ModItems.resistor);
		ModGameRegistry.registerItem(ModItems.capacitor);
		ModGameRegistry.registerItem(ModItems.turbin);
		ModGameRegistry.registerItem(ModItems.led);
		ModGameRegistry.registerItem(ModItems.spring);
		ModGameRegistry.registerItem(ModItems.bearing);
		ModGameRegistry.registerItem(ModItems.coal_coke);
		ModGameRegistry.registerItem(ModItems.silicon);
		ModGameRegistry.registerItem(ModItems.electrolyt_paper);
		ModGameRegistry.registerItem(ModItems.salt);
		ModGameRegistry.registerItem(ModItems.natrium);
		ModGameRegistry.registerItem(ModItems.fluid_meter);
		ModGameRegistry.registerItem(ModItems.energy_meter);
		ModGameRegistry.registerItem(ModItems.fuse_elv);
		ModGameRegistry.registerItem(ModItems.fuse_lv);
		ModGameRegistry.registerItem(ModItems.fuse_nv);
		ModGameRegistry.registerItem(ModItems.fuse_hv);
		ModGameRegistry.registerItem(ModItems.schredder_crusher);
		ModGameRegistry.registerItem(ModItems.schredder_macerator);
		ModGameRegistry.registerItem(ModItems.sulfur);
		ModGameRegistry.registerItem(ModItems.plastic_plate);
		ModGameRegistry.registerItem(ModItems.raw_rubber_bottle);
		ModGameRegistry.registerItem(ModItems.rubber_bottle);
		ModGameRegistry.registerItem(ModItems.crude_steel);
		ModGameRegistry.registerItem(ModItems.cardboard_sheet);
		ModGameRegistry.registerItem(ModItems.lime);
		ModGameRegistry.registerItem(ModItems.hard_drive);
		ModGameRegistry.registerItem(ModItems.network_configurtor);
		ModGameRegistry.registerItem(ModItems.structure_cladding_pane);
		ModGameRegistry.registerItem(ModItems.cement);
		ModGameRegistry.registerItem(ModItems.copper_coated_plate);
		ModGameRegistry.registerItem(ModItems.tined_copper_coated_plate);
		ModGameRegistry.registerItem(ModItems.circuit_board);
		ModGameRegistry.registerItem(ModItems.aluminium_disc);
		ModGameRegistry.registerItem(ModItems.data_disc);
		ModGameRegistry.registerItem(ModItems.ground_flesh);
		ModGameRegistry.registerItem(ModItems.ground_plants);
		ModGameRegistry.registerItem(ModItems.sulphurous_residue);
		ModGameRegistry.registerItem(ModItems.lime_dust);
		ModGameRegistry.registerItem(ModItems.slag);
		ModGameRegistry.registerItem(ModItems.fluorite_dust);
		ModGameRegistry.registerItem(ModItems.zirconium_dust);
		ModGameRegistry.registerItem(ModItems.zirconium_ingot);
		ModGameRegistry.registerItem(ModItems.zirconium_nugget);
		ModGameRegistry.registerItem(ModItems.zirconium_plate);
		ModGameRegistry.registerItem(ModItems.tpo_zirconium_dust);
		ModGameRegistry.registerItem(ModItems.slag_dust);
		ModGameRegistry.registerItem(ModItems.vanadium_oxid);
		ModGameRegistry.registerItem(ModItems.aluminium_oxid);
		ModGameRegistry.registerItem(ModItems.metallic_glass_ingot);
		ModGameRegistry.registerItem(ModItems.metallic_glass_nugget);
		ModGameRegistry.registerItem(ModItems.metallic_glass_plate);
		ModGameRegistry.registerItem(ModItems.cut_dried_peat);
		ModGameRegistry.registerItem(ModItems.dried_peat_pellets);
		ModGameRegistry.registerItem(ModItems.rayon_fibers);
		ModGameRegistry.registerItem(ModItems.carbon_fibers);
		ModGameRegistry.registerItem(ModItems.carbon_fabric);
		ModGameRegistry.registerItem(ModItems.carbon_plate);
		ModGameRegistry.registerItem(ModItems.tar_lump);
		ModGameRegistry.registerItem(ModItems.flax_straw);
		ModGameRegistry.registerItem(ModItems.scrutched_flax);
		ModGameRegistry.registerItem(ModItems.flax_fibers);
		ModGameRegistry.registerItem(ModItems.stone_dust);
		ModGameRegistry.registerItem(ModItems.clay_powder);
		ModGameRegistry.registerItem(ModItems.dried_meat);
		
		// register Functional Items
		ModGameRegistry.registerItem(ModItems.lever_element);
		ModGameRegistry.registerItem(ModItems.button_element);
		ModGameRegistry.registerItem(ModItems.lamp_element);
		
		// World Generation Settings (Adding Features to the specific Biomes)
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.COPPER_ORE);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.TIN_ORE);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.TIN_ORE_EXTRA, Category.JUNGLE);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.TIN_ORE_EXTRA, Category.SAVANNA);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.NICKEL_ORE);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.SILVER_ORE);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.SILVER_ORE_EXTRA, Category.JUNGLE);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.SILVER_ORE_EXTRA, Category.EXTREME_HILLS);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.SULFUR_ORE, Category.NETHER);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.BAUXIT_STONE_ORE, Category.JUNGLE);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.WOLFRAM_STONE_ORE);
		ModGameRegistry.addFeatureToBiomes(Decoration.LAKES, ModConfiguredFeatures.SULFUR_LAKE, Category.NETHER);
		ModGameRegistry.addFeatureToBiomes(Decoration.LAKES, ModConfiguredFeatures.SULFUR_LAKE_LARGE, Category.NETHER);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.FLUORITE_CRYSTALS);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.ZIRCON_CRYSTALS);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_DECORATION, ModConfiguredFeatures.SALT_SAND_ORE);
		ModGameRegistry.addFeatureToOverworldBiomes(Decoration.UNDERGROUND_DECORATION, ModConfiguredFeatures.LIMESTONE_ORE);
		
		// TODO
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.OIL_DEPOT, Category.DESERT);
		ModGameRegistry.addFeatureToBiomes(Decoration.UNDERGROUND_ORES, ModConfiguredFeatures.OIL_DEPOT, Category.OCEAN);
				
		// Trees TODO: Rubber Tree Models
		ModGameRegistry.addFeatureToBiomes(Decoration.VEGETAL_DECORATION, ModConfiguredFeatures.RUBBER_TREE, Biomes.SWAMP_HILLS, Biomes.JUNGLE, Biomes.JUNGLE_EDGE, Biomes.JUNGLE_HILLS, Biomes.MODIFIED_JUNGLE, Biomes.MODIFIED_JUNGLE_EDGE);
		ModGameRegistry.addFeatureToRemove(Decoration.VEGETAL_DECORATION, Features.ACACIA, Category.SAVANNA);
		ModGameRegistry.addFeatureToBiomes(Decoration.VEGETAL_DECORATION, ModConfiguredFeatures.ACACIA_TREE, Category.SAVANNA);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.FANCY_OAK);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.FANCY_OAK_BEES_0002);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.FANCY_OAK_BEES_002);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.FANCY_OAK_BEES_005);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.OAK_BADLANDS);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.OAK_BEES_0002);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.OAK_BEES_002);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.OAK_BEES_005);
//		ModGameRegistry.addFeatureToRemoveInOverworld(Decoration.VEGETAL_DECORATION, Features.OAK);
//		ModGameRegistry.addFeatureToBiomes(Decoration.VEGETAL_DECORATION, ModConfiguredFeatures.OAK_TREE_EXTRA, Biomes.FOREST, Biomes.FLOWER_FOREST, Biomes.WOODED_HILLS);
		
	}

	@SubscribeEvent
	public static void onBlocksRegistry(final RegistryEvent.Register<Block> blockRegistryEvent) {
		IForgeRegistry<Block> registry = blockRegistryEvent.getRegistry();
		Block[] blocksToRegister = ModGameRegistry.getBlocksToRegister();
		registry.registerAll(blocksToRegister);
	}
	
	@SubscribeEvent
	public static void onItemsRegistry(final RegistryEvent.Register<Item> itemRegistryEvent) {
		IForgeRegistry<Item> registry = itemRegistryEvent.getRegistry();
		Item[] itemsToRegister = ModGameRegistry.getItemsToRegister();
		registry.registerAll(itemsToRegister);
	}
	
}
