modLoader="javafml"
loaderVersion="[33,)"

license="All rights reserved"
issueTrackerURL="https://github.com/M-Marvin/MCMOD-RedTec/issues"

[[mods]]
modId="redtec"
version="0.5-pre"
displayName="RedTec"
displayURL="https://github.com/M-Marvin/MCMOD-RedTec"
credits="M_Marvin, Hase222 (McStockWeintraube)"
authors="M_Marvin, Hase222 (McStockWeintraube)"
logoFile="logo.png"

updateJSONURL="https://github.com/M-Marvin/MCMOD-RedTec/blob/main/ModUpdate.json"

description='''
Ein Mod der diverse neue Baumaterialien, Items, Resourcen und Maschinen hinzufügt.
Unter anderem Elektrizitäfct, Rezepte mit Flüssigkeiten und neue Erze.
'''