modLoader="javafml"
loaderVersion="[33,)"

license="All rights reserved"
issueTrackerURL="https://github.com/M-Marvin/MCMOD-Industria/issues"

[[mods]]
modId="industria"
version="0.8-prerelease"
displayName="Industria"
displayURL="https://github.com/M-Marvin/MCMOD-Industria"
authors="M_Marvin, Hase222 (McStockWeintraube)"
logoFile="logo.png"

updateJSONURL="https://m-marvin.github.io/MCMOD/Industria/download/versions.json"

description='''
Elektrizitaet, diverse neue Produktionsmaschienen zur automatisierung, viele neue Redstone Elemente und Resourcen.
'''