{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m_marvin.industriacore",
    "module": "IndustriaCore-1.20",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "IndustriaCore-1.20-1.0.jar",
          "url": "IndustriaCore-1.20-1.0.jar",
          "size": 3341668,
          "sha512": "ca11056419ae9a4c2525cb5713087ddd16c2c3e80d610c4c8e89fd74e89761750f047e539217f3f6d61d0db12af87e83bf1600b0feaf923ae7549881c564a1ca",
          "sha256": "6a2416349b7ac68950a81136fe3374e926f9cc85687ee1c12e8a6884434603c1",
          "sha1": "dfafca8771e5e3eca6bb2acff44ae7e654b5ccca",
          "md5": "f179750d5a44ba80c493fa2a4b9c781d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.valkyrienskies.core",
          "module": "api",
          "version": {
            "requires": "1.1.0+2b2f93f793"
          }
        },
        {
          "group": "curse.maven",
          "module": "kotlinforforge-351264",
          "version": {
            "strictly": "4630525_mapped_parchment_2023.08.13-1.20.1",
            "requires": "4630525_mapped_parchment_2023.08.13-1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "valkyrienskies-258371",
          "version": {
            "strictly": "4654328_mapped_parchment_2023.08.13-1.20.1",
            "requires": "4654328_mapped_parchment_2023.08.13-1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.1.44_mapped_parchment_2023.08.13-1.20.1_at_f355f9a9b6103b943cb53a9767a2635a1e86bd18"
          }
        },
        {
          "group": "com.github.M-Marvin",
          "module": "LIBRARY-NGLink",
          "version": {
            "requires": "844e6813c7e61b5127bead6deb7cea93990a24a3"
          }
        },
        {
          "group": "com.github.M-Marvin",
          "module": "LIBRARY-UnifiedVectors",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        },
        {
          "group": "curse.maven",
          "module": "atlasviewer-633577",
          "version": {
            "strictly": "4597419_mapped_parchment_2023.08.13-1.20.1",
            "requires": "4597419_mapped_parchment_2023.08.13-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "IndustriaCore-1.20-1.0.jar",
          "url": "IndustriaCore-1.20-1.0.jar",
          "size": 3341668,
          "sha512": "ca11056419ae9a4c2525cb5713087ddd16c2c3e80d610c4c8e89fd74e89761750f047e539217f3f6d61d0db12af87e83bf1600b0feaf923ae7549881c564a1ca",
          "sha256": "6a2416349b7ac68950a81136fe3374e926f9cc85687ee1c12e8a6884434603c1",
          "sha1": "dfafca8771e5e3eca6bb2acff44ae7e654b5ccca",
          "md5": "f179750d5a44ba80c493fa2a4b9c781d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "IndustriaCore-1.20-1.0.jar",
          "url": "IndustriaCore-1.20-1.0.jar",
          "size": 3341668,
          "sha512": "ca11056419ae9a4c2525cb5713087ddd16c2c3e80d610c4c8e89fd74e89761750f047e539217f3f6d61d0db12af87e83bf1600b0feaf923ae7549881c564a1ca",
          "sha256": "6a2416349b7ac68950a81136fe3374e926f9cc85687ee1c12e8a6884434603c1",
          "sha1": "dfafca8771e5e3eca6bb2acff44ae7e654b5ccca",
          "md5": "f179750d5a44ba80c493fa2a4b9c781d"
        }
      ]
    }
  ]
}
