buildscript {
	repositories {
		gradlePluginPortal()
		// These repositories are only for Gradle plugins, put any other repositories in the repository block further below
		maven {
			url 'https://repo.spongepowered.org/repository/maven-public/'
		}
	}
	dependencies {
		classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
	}
}

plugins {
	id 'maven-publish'
	id 'eclipse'

	id 'net.neoforged.moddev.legacyforge' version '2.0.137'
}

allprojects {
    eclipse.project {
        natures 'org.eclipse.buildship.core.gradleprojectnature'
    }
}

apply plugin: 'maven-publish'

base {
	archivesName = "${archives_base_name}-${mod_version}"
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(21)
}

legacyForge {
	version = "${minecraft_version}-${forge_version}"

	// Validate AT files and raise errors when they have invalid targets
	// This option is false by default, but turning it on is recommended
	validateAccessTransformers = true

	runs {
		client {
			client()
		}
		data {
			data()
		}
		server {
			server()
		}
	}

	mods {
		// Should this be vsch instead of testproject? I'm not sure
		testproject {
			sourceSet sourceSets.main
		}
	}
}

mixin {
//	add sourceSets.main, 'mixins.industriacore.refmap.json'
//	config 'mixins.industriacore.util.json'
//	config 'mixins.industriacore.ssdplugin.json'
}

repositories {
	mavenCentral()
	mavenLocal()

	maven { // mixins
        url = 'https://repo.spongepowered.org/repository/maven-public/'
        content {
        	includeGroup "org.spongepowered"
        }
    }
    
	maven {
		name = "ParchmentMC"
		url = "https://maven.parchmentmc.org"
	}
	
	// Custom libraries, adding one github repository somehow gives access to all of them ...
	maven {
		url 'https://maven.pkg.github.com/m-marvin/library-unifiedvectors'
		credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
        }
	}

}

dependencies {
	// region mixins
	annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
	compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
	jarJar(implementation("io.github.llamalad7:mixinextras-forge:0.5.0")) {
		version {
			strictly '[0.5.0,)'
			prefer '0.5.0'
		}
	}
	// endregion

    implementation("dev.lukebemish:codecextras:${codec_extras_version}") {
//        capabilities {
 //           requireFeature('minecraft-neoforge')
  //      }
    }

	// region Industria deps
	jarJar(implementation(additionalRuntimeClasspath("de.m_marvin.electronflow:tvnl-nna:${tvnl_nna_version}")))
	jarJar(implementation(additionalRuntimeClasspath("de.m_marvin.univec:univec:${univec_version}")))
	jarJar(implementation(additionalRuntimeClasspath("de.m_marvin.unimap:unimap:${unimap_version}")))
	// endregion
	
}

configurations {
	shade
	implementation.extendsFrom shade
}

processResources {
	var replaceProperties = [
		mod_id          : mod_id,
		mod_name        : mod_name,
		mod_license     : mod_license,
		mod_version     : mod_version,
		mod_authors     : mod_authors,
		mod_description : mod_description,

		minecraft_version       : minecraft_version,
		minecraft_version_range : minecraft_version_range,
		forge_version           : forge_version,
		forge_version_range     : forge_version_range,
		loader_version_range    : loader_version_range,
	]

	inputs.properties replaceProperties

	filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
		expand replaceProperties + [project: project]
	}
}

jar {
	manifest {
		attributes([
            'Specification-Title'	: mod_id,
	        'Specification-Vendor'		: mod_authors,
	        'Specification-Version'		: '1', // We are version 1 of ourselves
	        'Implementation-Title'		: project.name,
	        'Implementation-Version'	: project.jar.archiveVersion,
	        'Implementation-Vendor'		: mod_authors,
	        'Implementation-Timestamp'	: new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
//	        'MixinConfigs'				: "mixins.industriacore.refmap.json" // TODO: figure out why the MixinConfigs field did not add automatically might work?
		])
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

publishing {
	
}