# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

## idk what this is ... just dont touch it ...

archives_base_name=nodenet

## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47.4,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties

mod_id=nodenet
mod_name=Nodal Energy Networks
mod_license=All Rights Reserved
mod_version=0.1.0_build0
mod_group_id=de.m_marvin.nodenet
mod_authors=M_Marvin
mod_description=TODO

## Dependencies

univec_version=1.9.0
unimap_version=0.2-beta
tvnl_nna_version=0.1-beta-SNAPSHOT
codec_extras_version=3.0.0
