buildscript {
	repositories {
		gradlePluginPortal()
		// These repositories are only for Gradle plugins, put any other repositories in the repository block further below
		maven {
			url 'https://repo.spongepowered.org/repository/maven-public/'
		}
	}
	dependencies {
		classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'

		// Make sure this version matches the one included in Kotlin for Forge
		classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
	}
}

plugins {
	id 'maven-publish'
	id 'eclipse'

	id 'net.neoforged.moddev.legacyforge' version '2.0.137'
}

allprojects {
    eclipse.project {
        natures 'org.eclipse.buildship.core.gradleprojectnature'
    }
}

// While _we_ don't use kotlin, this is still needed for VS to compile properly
// (It used to be included transitively, but now we don't use a transitive VS dep)
apply plugin: "org.jetbrains.kotlin.jvm"

apply plugin: 'maven-publish'

base {
	archivesName = "${archives_base_name}-${mod_version}"
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(17)
}

legacyForge {
	version = "${minecraft_version}-${forge_version}"

	// Validate AT files and raise errors when they have invalid targets
	// This option is false by default, but turning it on is recommended
	validateAccessTransformers = true

	runs {
		client {
			client()
		}
		data {
			data()
		}
		server {
			server()
		}
	}

	mods {
		// Should this be vsch instead of testproject? I'm not sure
		testproject {
			sourceSet sourceSets.main
		}
	}
}

mixin {
	add sourceSets.main, 'mixins.industriacore.refmap.json'
	config 'mixins.industriacore.util.json'
	config 'mixins.industriacore.ssdplugin.json'
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
	mavenCentral()
	mavenLocal()

	maven { // mixins
        url = 'https://repo.spongepowered.org/repository/maven-public/'
        content {
        	includeGroup "org.spongepowered"
        }
    }
    
    // Mods from curse forge (such as JEI)
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    
//	maven {
//		url = "https://modmaven.dev/"
//	}

	// Should mirror a lot of our deps, including Create, CC:T, KFF? and anything else VS has in its dev enviroment
	// However we still include the other mavens, just in case it goes down
	maven {
		name = "Valkyrien Skies Internal"
		url = "https://maven.valkyrienskies.org"
		content {
			excludeGroup("org.spongepowered")
			excludeGroup("thedarkcolour")
		}
	}
	
	// Mainly for create flywheel and colorwheel
    maven {
        name "createmod maven"
        url "https://maven.createmod.net/"
    }
    
	maven {
		name = "ParchmentMC"
		url = "https://maven.parchmentmc.org"
	}

	// Required to make VS2 work
	maven {
		name = "Kotlin for Forge"
		url = "https://thedarkcolour.github.io/KotlinForForge/"
		content {
			includeModule("thedarkcolour", "kotlinforforge")
		}
	}
	
	// Custom libraries, adding one github repository somehow gives access to all of them ...
	maven {
		url 'https://maven.pkg.github.com/m-marvin/library-unifiedvectors'
		credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
        }
	}

}

dependencies {
	// region mixins
	annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
	compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
	jarJar(implementation("io.github.llamalad7:mixinextras-forge:0.5.0")) {
		version {
			strictly '[0.5.0,)'
			prefer '0.5.0'
		}
	}
	// endregion

	// region Valkyrien Skies
	implementation("org.valkyrienskies.core:api:${vs_core_version}") { transitive = false
		exclude group: 'org.joml', module: ''
	}
	implementation("org.valkyrienskies.core:internal:${vs_core_version}") { transitive = false
		exclude group: 'org.joml', module: ''
	}
	implementation("org.valkyrienskies.core:util:${vs_core_version}") { transitive = false
		exclude group: 'org.joml', module: ''
	}
	implementation("org.valkyrienskies.core:impl:${vs_core_version}") { transitive = false
		exclude group: 'org.joml', module: ''
	}
	modApi("org.valkyrienskies:valkyrienskies-120-forge:${vs2_version}") { transitive = false
		exclude group: 'org.valkyrienskies.core', module: ''
	}
	// endregion

	// region VS deps
	implementation "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
	compileOnly("org.joml:joml:1.10.4")
	compileOnly("org.joml:joml-primitives:1.10.0")
	modImplementation "thedarkcolour:kotlinforforge:4.11.0"
	// endregion
	
	// region Industria deps
	jarJar(implementation(additionalRuntimeClasspath("de.m_marvin.electronflow:tvnl-nna:${tvnl_nna_version}")))
	jarJar(implementation(additionalRuntimeClasspath("de.m_marvin.univec:univec:${univec_version}")))
	jarJar(implementation(additionalRuntimeClasspath("de.m_marvin.unimap:unimap:${unimap_version}")))
	// endregion
	
	// region compat
	modImplementation("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
	modImplementation("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
	// endregion
	
	// region debugging
	modRuntimeOnly("curse.maven:jei-238222:6075247")
	// vvv Remove before starting server vvv
	modRuntimeOnly("curse.maven:atlasviewer-633577:4882554")
	modRuntimeOnly("curse.maven:oculus-581495:6020952")
	modRuntimeOnly("curse.maven:embeddium-908741:5681725")
	// endregion
	
}

configurations {
	shade
	implementation.extendsFrom shade
}

processResources {
	var replaceProperties = [
		mod_id          : mod_id,
		mod_name        : mod_name,
		mod_license     : mod_license,
		mod_version     : mod_version,
		mod_authors     : mod_authors,
		mod_description : mod_description,

		minecraft_version       : minecraft_version,
		minecraft_version_range : minecraft_version_range,
		forge_version           : forge_version,
		forge_version_range     : forge_version_range,
		loader_version_range    : loader_version_range,

		// This property isn't used right now in mods.toml
		vs2_version: vs2_version.split("\\+").first(), // gradle.properties will have git commit version, but public releases won't
	]

	inputs.properties replaceProperties

	filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
		expand replaceProperties + [project: project]
	}
}

jar {
	manifest {
		attributes([
            'Specification-Title'	: mod_id,
	        'Specification-Vendor'		: mod_authors,
	        'Specification-Version'		: '1', // We are version 1 of ourselves
	        'Implementation-Title'		: project.name,
	        'Implementation-Version'	: project.jar.archiveVersion,
	        'Implementation-Vendor'		: mod_authors,
	        'Implementation-Timestamp'	: new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
	        'MixinConfigs'				: "mixins.industriacore.refmap.json" // TODO: figure out why the MixinConfigs field did not add automatically might work?
		])
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

publishing {
	
}